import 'package:ARshop_App/page/login.dart';
import 'package:ARshop_App/page/register.dart';
import 'package:ARshop_App/utils/consts.dart';

const password_label = 'รหัสผ่าน';
const confrim_password_label = 'ยืนยันรหัสผ่าน';
const email_label = 'อีเมล';
const username_label = 'ชื่อผู้ใช้งาน';
const example_email_hint = 'xxxxx@email.com';
const register_title = 'สมัครสมาชิก ARshop ';
const login_text = 'เข้าสู่ระบบ';
const emailHint = 'อีเมลผู้ใช้งาน';
const passwordHint = 'รหัสผ่านผู้ใช้งาน';
const forgetpass = 'ลืมรหัสผ่าน?';
const register_text = 'สมัครสมาชิก';
const hintpassword = '******';
const phone_number = 'เบอร์โทร';
const phone_number_label = 'เบอร์โทร';
const product_popular_label = 'สินค้ายอดฮิต';
const product_recommend_label = 'สินค้าแนะนำ';
const birthdate_label = 'วันเกิด';
const gender_label = 'เพศ';
const birthdate_select_hint = 'เลือก วัน/เดือน/ปีเกิด';
const profile_label = 'โปรไฟล์';
const purchase_order_label = 'คำสั่งซื้อสินค้าของฉัน';
const product_name = 'White Sofa';
final buttons = ['ภาพรวม', 'รายละเอียดสินค้า', 'รีวิว'];
const send_to = 'จัดส่งสินค้าไปยัง';
const address_customer = 'เขตลาดกระบัง 10520';
